name: Space Auto Update
on:
  push:
    paths:
      - 'avatars/**' # Спрацьовує, коли в папці avatars з'являється файл

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Pillow
        run: pip install Pillow

      - name: Process Map
        run: python scripts/process_map.py

      - name: Commit & Push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add main_map.png
          git commit -m "New astronaut on the map" || exit 0
          git push
