name: Space Auto Update
on:
  issues:
    types: [opened]

jobs:
  build:
    if: contains(github.event.issue.title, 'ADD_PFP')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Save image from issue
        run: |
          mkdir -p avatars
          echo "${{ github.event.issue.body }}" | base64 --decode > avatars/user_${{ github.event.issue.number }}.png

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Pillow
        run: pip install Pillow

      - name: Process Map
        run: python scripts/process_map.py

      - name: Commit & Push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add main_map.png
          git commit -m "Added astronaut from issue #${{ github.event.issue.number }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }} # Використовуємо наш секретний токен

      - name: Close Issue
        run: gh issue close ${{ github.event.issue.number }} --confirm
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
